### PR TITLE
fold items belonging to checkboxes, fix css for jumpy jquery 

### PR DESCRIPTION
**Pull request by alexpos**
This is inspired by something in functions.php in the options-framework-theme. It was also requested [here](http://aquagraphite.com/2011/09/slightly-modded-options-framework/).

What does it do: it ads options for a checkbox. If a checkbox is unchecked, sub-items are hidden. 

How does it work: Add "folds" => "something" to a checkbox, and "fold"=>"name-of-the-checkbox" to the sub-items.  Admin-interfaces ads some classes, and css hides the sub-items. Clicking the check-box makes it appear again.

### CODE REVIEW

**Comment by syamilmj** [comment]
Hi plovs,

Can you include a couple of options to show how this is used in theme? I would like to test them out.

Probably send in another request if you don't mind?

Cheers

**Comment by alexpos** [comment]
Alright, added an example

**Comment by syamilmj** [comment]
Hey, quick question.

If you have multiple of options you wanted to fold, will giving them each `fold => checkbox_id` do it?

I'm going to test out your mod on my localhost :)

**Comment by alexpos** [comment]
yes, use as many options as you want, just make sure they all point to the (same) correct checkbox_name, NOT id!

**Pull request merged**
