### PR TITLE
Added Google Font Preview Functionality / Fixed Google Font Selects

### PR DESCRIPTION
**Pull request by dhechler**
Google fonts can now use weight and italic for each font. To use them define them like so:

```
     "options" => array(
            "none" => "Select a font",
            "Lato:900" => "Lato", // Ultra bold
            "Lobster+Two:700italic" => "Lobster Two Bold Italic", // Bold Italic
            "Playfair+Display:900italic" => "Playfair Display Black Italic" // Ultra Bold Italic
        )
```

Also fixed an issue with google fonts that if you had more than one google font listed on the same tab, it would not select the correct value for the first google font or show the preview.

### CODE REVIEW

**Comment by partnuz** [comment]
The thing is it's not very versatile. It would be better if user could choose between different font-weight and type.

**Comment by dhechler** [comment]
This is for the developer to define the fonts in the backend. Not for the front end  user to choose between font weights

## 

David Hechler

**Comment by awps** [comment]
+1 for partnuz. I personally don't like this way.

**Comment by dhechler** [comment]
Sorry you feel that way. Seems to be in line with the way Google would like their fonts included and formatted. Right now you don’t have an option to include different font weights. Hope you come up with something that suits the way you like to code.

## 

David Hechler

**Comment by dovy** [comment]
@dhechler Just finished porting my Google Fonts Typography module to my Smof fork. If you wanted to see it: https://github.com/SimpleRain/SimpleOptions/releases/tag/0.1.2

I'm find if someone wants to backwards implement it to SMOF i support. Just will take some doing. SOF has more.. options.

**Comment by dhechler** [comment]
Off topic a bit and we can start a new conversation for it, but is SOF theme base? Basically, does it save options based on the theme you are using or is it theme agnostic? Id like to see an option to do either.

## 

David Hechler

**Comment by dovy** [comment]
Agnostic as that's how the Wordpress settings API works. No way to bypass that really unless you define a custom suffix. Guess I could do it... What would be the use case?

Dovy

**Comment by dhechler** [comment]
I guess my question was more leading than i wanted it to be. So SMOF stores the data as theme_name_smof_options (just remembering that off the top of my head, not literal). So when I change a theme, i lose the options.

## 

David Hechler

**Comment by dovy** [comment]
That's how the setting API works. I guess I could make it the same. Hmm. 

Dovy Paukstys

**Comment by dhechler** [comment]
I would rather it be theme agnostic. Especially if i have child themes i am changing from and to due to an option i have set in the framework :)

## 

David Hechler

**Comment by dovy** [comment]
Do you want to try and code that in?

Dovy

**Comment by dovy** [comment]
@dhechler Never mind, I was wrong. It's stationary. If you set $args['opt_name'] when you declare SOF, it will work in any theme with that ID.

So the SOF fork works exactly as you requested without me even knowing it. Thanks.

**Comment by dhechler** [comment]
Im not so worried about the plugin not working when switching themes as i am the data being stored in the options table as theme_name_SOF_options rather than just SOF_options (again, just theorizing on the name, not in front of my DB) and the data being tied to the current theme rather than the site itself. Again, not saying your plugin does that, just wondering which it is. :)

## 

David Hechler

**Comment by dovy** [comment]
@dhechler Let me explain.

There is a variable you define when you call the option framework. This variable becomes the name in which the option framework is in the DB.

Let's take for example this: 

```
$args['opt_name'] = 'twenty_eleven';
```

This will store all the settings in this one variable. Here's the example code for updating that option:

```
update_option($this->args['opt_name'], $this->options);
```

If you wanted to keep it global despite what theme you use, but be on the same site, you define it as a key of your choosing.

If you want it to be unique to the theme, then you'd set the variable to be:

```
$args['opt_name'] = strtolower(str_replace(" ", "", get_current_theme()))
```

In this way it would be dynamic for every theme. Either way, it is global to the key you set. It's up to you what you set that key to be.  ;)

**Comment by dhechler** [comment]
Ahhhhhh. Thats awesome. Thanks for that.

## 

David Hechler

**Comment by dovy** [comment]
@dhechler You're welcome. For further discussion or questions about SOF, please go to the SOF issue tracker here and post: https://github.com/SimpleRain/SimpleOptions/issues

Thanks! Let me know any other thoughts/ideas you may have (but over there, heh).

And maybe close this issue if you're questions are answered?

**Comment by dovy** [comment]
@dhechler Newest version I'm about to post to SOF defaults to the above code, and you define if you want it to be agnostic to themes and based off a key. Thanks for the idea.

;)

Don't forget to close this issue.

**Comment by dovy** [comment]
@dhechler Have a demo up you can try if you want of my typography option I used in SOF: http://simpleoptions.simplerain.com

**Pull request closed without merging**
