### PR TITLE
tuned om

### PR DESCRIPTION
**Pull request by valknarthing**
Hi,

Nice tool!
did some 'non-destructive' changes to your framework to use it easier in other projects.
Also started a WordPress PluginPlugin, which will make use of it (http://github.com/100hz/smofp).

Best Regards,
Sebastian

### CODE REVIEW

**Comment by syamilmj** [comment]
Hey looks good. What does this do basically? :)

**Comment by valknarthing** [comment]
Hmm, you can pretty easy define a wordpress plugin (with widgets & shortcodes) with one line in the plugin-main-file.php and an according options array. See https://github.com/100hz/smof-p-usage ...uses an installed smofp as "API"

Tried to leave your framework untouched, so it can be easily integrated, only the above changes were needed (till now)

**Comment by lenanghai** [comment]
one bug on this version !

The title in home control is replaced by "V" character ...fix it now !

**Comment by syamilmj** [comment]
@lenanghai  Do you want me to murder you?

**Comment by lenanghai** [comment]
oh no

**Pull request closed without merging**
