### PR TITLE
Keep Site URL Out of Database

### PR DESCRIPTION
**Pull request by jonahbron**
Here is the merged version.  Tested in a pure, fresh installation of WordPress.

### CODE REVIEW

**Comment by syamilmj** [comment]
Hey man,

I just merged your commits to the branch and also removed some of the conflicts (you probably missed them).

Also I've added you to collaborator's list, so you can make edits/push/merge without permission :)

Please do a final check on this branch if everything works perfectly then feel free to merge to master.

Cheers

**Comment by awps** [comment]
Also please update the version and add details in changelog.

Looks like a good update, but please test it and make sure that everything works fine, before you merge that.

**Comment by jonahbron** [comment]
All right, I'll do that.  Thank you gentlemen.

**Comment by jonahbron** [comment]
When you say "update the version", do you mean increment it to 1.4.4?

**Comment by jonahbron** [comment]
Tested and merged.

**Comment by syamilmj** [comment]
Good job mate :thumbsup: :)

**Pull request merged**
