### PR TITLE
Fixed the issue with undefined indexes.

### PR DESCRIPTION
**Pull request by dovy**
Forgot to make global $smof_data in of_save_options() (bad because i
compared against it) and also used the wrong variable for 2 hooks.

### CODE REVIEW

**Comment by dovy** [comment]
@Smartik89 @chadhenry @sy4mil

Fixed it! The issue was that I hadn't made global $smof_data in the of_save_options function, and thus when I tried to compare it never set the values. Wee.

Also fixed some hook variables I messed up.

Sorry for the grief!

**Comment by chadhenry** [comment]
@dovy is it just me? I'm seeing a huge number of notices and warning now on a fresh install

<pre>
Notice: Undefined index: media_upload_35 in C:\xampp\htdocs\theme1\wp-content\themes\Theme1\admin\classes\class.options_machine.php on line 617
.... ... ....
Notice: Undefined index: example_colorpicker in C:\xampp\htdocs\theme1\wp-content\themes\Theme1\admin\classes\class.options_machine.php on line 221
Warning: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\theme1\wp-content\themes\Theme1\admin\classes\class.options_machine.php:171) in C:\xampp\htdocs\theme1\wp-includes\option.php on line 568
Warning: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\theme1\wp-content\themes\Theme1\admin\classes\class.options_machine.php:171) in C:\xampp\htdocs\theme1\wp-includes\option.php on line 569
</pre>

**Comment by dovy** [comment]
@chadhenry Pull. Hehe. Forgot to add a  || !isset($smof_data[$k])

I had forgot to test with fresh installs.

**Comment by chadhenry** [comment]
@dovy no change. Same issues on fresh install. Tried it twice just to make sure...

**Comment by dovy** [comment]
Bah. I won't be near my computer for a few hours. I'll look as soon as I can. 

Dovy Paukstys
801.706.4076

**Comment by awps** [comment]
Yes, @chadhenry is right, there are a lot of "Undefined Index" notices, but they dissapear after page refresh, and this is a good sign. Options are populated with default values and this is good also. The only problem I see now is that the site url is replaced with a shortcode in media field. This is the last thing that need to be fixed before merge. After this merge we must do something to get rid of these notices that appear on first theme activation.

**Comment by dovy** [comment]
@chadhenry @Smartik89 Fixed the media issue in newest push.

Can't figure out this index issue. It's driving me mad. Can anyone else take a look?

**Comment by chadhenry** [comment]
@dovy I've been looking into this for awhile now, but I can't find the root cause either

**Comment by dovy** [comment]
Yea. It's really frustrating!

Dovy Paukstys

**Comment by awps** [comment]
@dovy, please close this pull-request and create a new one, but the query should be so:
From you: `head branch: master`
To original repo: `base branch: dovy-master`
These options are available on "pull request" page. 

P.S. Current Pull has conflicts that don't let me merge the code.

**Comment by dovy** [comment]
Will do.

**Pull request closed without merging**
