### PR TITLE
Here we go.

### PR DESCRIPTION
**Pull request by dovy**

### CODE REVIEW

**Comment by dovy** [comment]
@Smartik89 As you requested.

We just have to find why that initial undefined index error occurs!

**Comment by ink888** [comment]
yupez....Thanks @dovy for the prompt reply....! It seems to be more stable now...
I'm still looking for the way how to specify image dimension (width & height ) in the slider in the echo function...
Anyway, may I add another features to this framework?

**Comment by dovy** [comment]
@ello0o Explain why you would want/need that?

**Comment by awps** [comment]
Merged. Last test before I merge it into master branch, would be awesome. Just to make sure that everything works well.

**Comment by awps** [comment]
I think it's ready to merge in 'master'. @dovy if you have time, please download it from here https://github.com/sy4mil/Options-Framework/tree/dovy-master and do a last test to make sure that all is ok.

**Comment by dovy** [comment]
@Smartik89 Please do one last pull. I started making an example (external) item for the class_option_machine and found I needed to change things a little for the hooks to function (since wordpress hooks can't return a thing, _sigh_).

See: https://github.com/sy4mil/Options-Framework/pull/238

I'll continue to test to make sure it's ready for merge.

**Comment by awps** [comment]
@dovy, merged. Make sure to test if everything is ok, and let me know where we can merge the code to `master`.

**Comment by dovy** [comment]
@Smartik89 @sy4mil @chadhenry
Finally fixed the undefined indexes!

https://github.com/sy4mil/Options-Framework/pull/239

Issue was based in the core of SMOF, not the stuff I did. I added an isset check here and there and voila, no problems.

**Comment by awps** [comment]
I'll merge it right now to `dovy-master`... ;)

**Pull request merged**
