### PR TITLE
Various fixes, conversion to get_theme_mod(), fixed import, etc.

### PR DESCRIPTION
**Pull request by dovy**
@Smartik89

Added some to CSS to stop color picker from "jumping"

Updated various files to use the of_get_options instead of using the direct commands (previously get_option) so there's more consistency throughout.

~/admin/functions/functions.options.php, again, updated the direct reference of get_option() to of_get_options()

Renamed all comments that stated: @uses get_option() to get_theme_mod()

Removed the OPTION constant, since get_theme_mod does the prefix for the theme automatically.

Updated the BACKUP constant, since get_theme_mod does the prefix for the theme automatically.

Added check for key to get all get_theme_mods, or just a single for both get and set.

Added an option to ~/admin/functions/functions.interface.php that if the get_theme_mod is empty, fill it with the defaults. This will alleviate the errors that you see when you add SMOF to a theme not initialized with SMOF in place. IE, makes my life better and hopefully other devs. Previously you would have to reset options or the whole interface looked odd.

~/admin/functions/functions.interface.php, changed get_option references to use of_get_options for consistency. Also changed line 248 from $smof_data to $_POST['data'] to fix importing.

~/admin/functions/functions.options.php, again, updated the direct reference of get_option() to of_get_options()

~/admin/index.php - Removed the OPTIONS constant, get_theme_mod does this automatically.

### CODE REVIEW

**Comment by syamilmj** [comment]
Pushed to this branch - https://github.com/sy4mil/Options-Framework/tree/dovy-master

Didn't notice any issues so far. Great jobs!

Last check anyone? :)

**Comment by dovy** [comment]
@sy4mil You come back and finally people are interested in my code.  ;)

Thanks.

**Comment by dovy** [comment]
@sy4mil Honestly, the BACKUP constant isn't really needed now. We could just call it 'backups' and drop the constant, but I wasn't sure which way to go with that.

**Comment by awps** [comment]
One problem. I don't see default values on theme activation. "std" key is ignored, if I click Options Reset, all fields are populated with default values. Is this a new bug or not?

**Comment by dovy** [comment]
@Smartik89 That's the same problem I attempted to resolve with the ~/admin/functions/functions.interface.php change. Did your version before have the same issues? I may have missed something...

**Comment by awps** [comment]
@dovy, That's why I ask if is a new bug or not, because as I remember I had default values in my panel after theme activation. Maybe there is something we need to do after theme activation?
ie: http://codex.wordpress.org/Plugin_API/Action_Reference/after_setup_theme

P.S. I'm too tired to look into it right now. :P

**Comment by dovy** [comment]
@Smartik89 I can't duplicate it. I try renaming my theme folder, renaming my theme name, deactivating, reactivating. Nada. Can you duplicate it every time?

**Comment by awps** [comment]
Looks like this is specific only when a theme is first time activated. Now I don't have this. It works and default values are there. Strange. :D

**Comment by dovy** [comment]
Can anyone else verify? I'd prefer not to have to do a Wordpress re-install to debug this, hah.

**Comment by chadhenry** [comment]
@dovy  @Smartik89 I can confirm that 'std' is being ignored on a fresh WP install. Default values are only populated after clicking Options Reset.

**Comment by dovy** [comment]
Looking into it... I am confused, hah.

**Comment by syamilmj** [comment]
Perhaps take a look at this which I added - https://github.com/sy4mil/Options-Framework/blob/dovy-master/admin/classes/class.options_machine.php#L39

Doubt it causes the issue though :confused:

**Comment by dovy** [comment]
@sy4mil @Smartik89 @chadhenry I've resolved all the issues in this most recent commit. Please refer to above for extra details.

I've also added a few hooks for expanding the features of SMOF externally. Basically some do_action hooks. ;)

Let me know your thoughts. With all my tests everything is working perfectly.

P.S. This is a complete rewrite of my changes and I just moved a copy of the SMOF base, hence why the numerous image updates. Sorry about that. Shouldn't affect a thing.

**Comment by chadhenry** [comment]
@dovy I haven't done a complete and thorough test, but so far I can confirm that the issue with "std" not setting on a fresh WP install seems to be resolved.

I'm not sure if this is something new, but I'm noticing an issue with a div pushing through when "Home Settings" is selected. It seems related to this css: https://github.com/dovy/Options-Framework/blob/master/admin/assets/css/admin-style.css#L558

**Comment by dovy** [comment]
@Smartik89 P.P.S. With the hooks I just put in you could easily integrate your Sidebar generator without modifying SMOF. Very useful indeed.

Here are the hooks I made:

```
of_option_setup_before
of_option_setup_after
of_get_options_before
of_get_options_after
of_save_options_before
of_save_options_after
optionsframework_machine_before
optionsframework_machine_loop // Inside the loop, can you say custom values?
optionsframework_machine_after
optionsframework_admin_init_before
optionsframework_admin_init_after
of_style_only_after
of_load_only_after
```

I have some custom things I need to hook into SMOF. I was doing this manually, but I'd much rather use a hook and save myself modifying the SMOF core. I hope it is a welcome addition.

**Comment by dovy** [comment]
@chadhenry I see that. I didn't change that CSS. I can't find it in any of my commits. Perhaps there's an extra closing div somewhere? I'll look.

**Comment by dovy** [comment]
@chadhenry Indeed, it is exactly line: https://github.com/dovy/Options-Framework/blob/master/admin/assets/css/admin-style.css#L562

Seems like it could have been caused by the addition of the SMOF footer bar. https://github.com/sy4mil/Options-Framework/commit/7e20f9b1c13da60b3d3b9dc399a7268425e7f291

I'm not sure though. I can commit the change to remove the padding on like 562, but I'd like other to test on IE and such before doing so. Otherwise I may make it worse. I am a mac only guy over here.  ;)

The offensive CSS is found on line 562 of admin-styles.css:

```
padding: 10px 20px 0px 20px;
```

I have verified that this resolves the issue in Chrome, Firefox, Opera, and Safari on my Mac.

**Comment by dovy** [comment]
Pushed the css fix. Please test on all major PC browsers.  :)

**Comment by chadhenry** [comment]
That seems to have fixed it for me on Win7 Chrome, FF, Safari, IE8-10

**Comment by chadhenry** [comment]
@dovy  by the way, great job with the commits and thanks for your continued contributions!

**Comment by dovy** [comment]
@chadhenry Don't praise me too much. I intend to make a killing with SMOF as the base of my themes. It's simply the best option framework out there.

**Comment by dovy** [comment]
@chadhenry Found the real issue with the padding. It's resolved now. My bad.

**Comment by chadhenry** [comment]
@dovy lol you said it 30 seconds before I could!

**Comment by dovy** [comment]
@sy4mil @Smartik89 @chadhenry Unless you can find some issues, I think we're ready to merge. Let me know if you find any other concerns.

It's working perfectly for my needs!

**Comment by chadhenry** [comment]
@dovy @sy4mil @Smartik89 I've tested the latest commit on a fresh WP install and played around a bit and I'm not seeing any obvious issues. It looks like it's good to go if you wanted to merge the changes.

**Comment by awps** [comment]
Tested in a fresh wp installation and it works. I'll merge it right now. 
Next step,  we must find a solution for all these notices that appear to first theme activation.

**Comment by awps** [comment]
Ohh, sh*t it doesn't work. There are a lot of notices and they don't dissapear after "Theme Options" button is pressed. Also this stops media uploader to work properly.

**Comment by awps** [comment]
@dovy, I canceled all your changes. Please verify it again. I don't know why, but "Undefined index:" notices, are there, they don't dissapear and this stops Media Uploader from working properly.

**Comment by chadhenry** [comment]
@dovy I forgot to enable wp_debug before - Now I'm seeing about 20 Undefined index and Undefined variable notices as well

**Comment by dovy** [comment]
@chadhenry @Smartik89 I'm on it. Odd, I don't get a single undefined index. Hmm.

**Comment by dovy** [comment]
Ok, so the issue is smof_data not being populated with the variables that have an empty std value. Odd. Looking into why that's happening. At this moment I have no idea, hah.

**Pull request merged**
