### PR TITLE
Bye undefined indexes!

### PR DESCRIPTION
**Pull request by dovy**
Resolved the last known issue.

### CODE REVIEW

**Comment by awps** [comment]
Merged. Hope everything is ok now. :)

**Comment by awps** [comment]
Works like a charm. I'm going to merge this to `master`.

**Comment by syamilmj** [comment]
Fantastic job guys :) :+1:

**Comment by dovy** [comment]
Haha, sweet. 

Now we need to internationalize SMOF, lol. I've done that for my theme, but we should do it for the core.

**Comment by awps** [comment]
Updated and merged to master. Great job.

**Pull request merged**
