### PR TITLE
Keep Site URL Out of Database

### PR DESCRIPTION
**Pull request by jonahbron**
Often, migrating a WordPress site can be made very difficult for a developer because the site URL is in the database in so many different places.  This change adds the ability to filter data on save and load, and adds filters for stripping out the site URL from strings and replacing it with a pseudo-shortcode on save, and vice versa on load.

### CODE REVIEW

**Comment by partnuz** [comment]
But what happened to BACKUP field ?
Also have you tested it with official import/export plugin ?

**Comment by jonahbron** [comment]
Oops, you're right about the backup, my mistake; fixed that.  I don't understand your second question?  I didn't know it integrated with the import/export plugin, but I don't believe I've changed the way it would interface with it, have I?

**Comment by partnuz** [comment]
Basically the import plugin must use do_shortcode function to import data with shortcodes otherwise it will not download images thus requiring to do everything manually which is contrary to the point of this patch. Please, test it with online environment and share the results.

**Comment by jonahbron** [comment]
I think there may be a communication breakdown, perhaps I wasn't totally clear.  It's not using actual shortcodes, it's just replacing the site URL with a special keyword when saving from the database, hence the term "pseudo-shortcode".  Did you get a chance to look at the filters file?

https://github.com/jonahbron/Options-Framework/blob/master/admin/functions/functions.filters.php

**Comment by syamilmj** [comment]
@partnuz did u get to test this patch?

**Comment by jonahbron** [comment]
Yes, I integrated it directly into my project and it worked perfectly after that last commit.

**Comment by partnuz** [comment]
@sy4mil I didn't test it and still don't know whether it works with official import plugin.

**Comment by syamilmj** [comment]
Since you were editing from the 1.4.0 version, there were a few conflicts that needs to be fixed before I can merge this to master. I've created a new branch here - https://github.com/sy4mil/Options-Framework/tree/jonahbron-master

Please fix all the conflicts ( marked by <<<< ) in the files you edited and send a pull request to that branch and I'll merge it to the master.

Closing this one so we can focus on that branch.

Cheers

**Comment by jonahbron** [comment]
Ah, I didn't realize you were addressing someone else :)

**Comment by syamilmj** [comment]
No worries :)

Let me know when you're done with this fix. This looks like a good improvement, I'm sure many will benefit from it.

Cheers

**Pull request closed without merging**
