### PR TITLE
Update class.options_machine.php

### PR DESCRIPTION
**Pull request by haikbvn**

### CODE REVIEW

**Comment by dovy** [comment]
Well, your radios use integers right now, so that's what we ended up using. This is just a way to reflect the same result.

If you want it your way as outlined above, perhaps you should update your radios?

**Comment by dovy** [comment]
@Smartik89 @haikbvn I added this in the most recent pull request, but in a different way.

Look here: https://github.com/dovy/Options-Framework/blob/01f49b03ebce80f19e83bcaa1ab00a95623b2cca/admin/classes/class.options_machine.php#L155-L158

I made it so if the ID of the given select array is not numeric, you use that as the ID. Otherwise, you just return the actual value.

I think this will be the best of both worlds. Feel free to close this pull request.

**Comment by haikbvn** [comment]
Thank so much! :-)

**Comment by awps** [comment]
@haikbvn, at the moment these changes are in this branch https://github.com/sy4mil/Options-Framework/tree/dovy-master
Soon they will be merged to default branch, we do some testings now.

**Pull request closed without merging**
