### PR TITLE
Fixed the "bugs"

### PR DESCRIPTION
**Pull request by dovy**
Did a better fix for lost indexes. Also introduced $smof_details, whish is the same as $of_options but has the data sorted by key. ;)

### CODE REVIEW

**Comment by dovy** [comment]
Also resolves https://github.com/sy4mil/Options-Framework/issues/251, as the commit mentions.

**Comment by chadhenry** [comment]
Hmm, I'm getting a few errors on a fresh install

```
Notice: Undefined index: media_upload_35 in C:\xampp\htdocs\theme1\wp-content\themes\Theme1\framework\admin\classes\class.options_machine.php on line 740

Notice: Undefined index: media_upload_356 in C:\xampp\htdocs\theme1\wp-content\themes\Theme1\framework\admin\classes\class.options_machine.php on line 740

Notice: Undefined index: pingu_slider in C:\xampp\htdocs\theme1\wp-content\themes\Theme1\framework\admin\classes\class.options_machine.php on line 796
```

**Comment by dovy** [comment]
@chadhenry Let me take a look at that again, heh. You're sure your using my fork code?

**Comment by chadhenry** [comment]
I used dovy master, is that not the right one? I'll test again just to make sure..

**Comment by dovy** [comment]
@chadhenry I think I just fixed it for real now. Heh. The errors went really deep.

### Also! With these new changes, you can add a value at any time to $of_options and it will be populated by the default if you haven't had it before. No more undefined indexes!

**Comment by chadhenry** [comment]
@dovy excellent work! I think all issues are resolved with the latest commit. I think it's ready to merge.

**Comment by dovy** [comment]
@chadhenry Now, as an added bonus, you can access $smof_details[KEY] from anywhere on the site to see all the possible options. No need to initiate a class_options_machine. I find this pretty useful, heh.

**Comment by awps** [comment]
Great job, mate. Respect for what you do. ;)

**Comment by dovy** [comment]
@Smartik89 Just want to fix the issues I introduce, hah.

Hopefully we'll get things going as we need to.

**Comment by partnuz** [comment]
If you update $of_options and don't visit admin panel, the problem still occurs. 
To reproduce do the following:
1. Add new option to $of_options
2. Try to access the option in the theme like echo $smof_data['option_name'] in for instance functions.php
Option is undefined unless visiting admin section.

**Comment by dovy** [comment]
Is that really an issue? Most users won't be adding a new option, only developers and most of the time they'll be in the admin panel. Do you feel otherwise? I'm not sure if this is a bug that needs fixing, but I want to hear your thoughts.

**Comment by partnuz** [comment]
Unfortunately it is important issue. Especially for themeforest theme developers. Basically notices and warnings cause automatic rejection.

**Comment by chadhenry** [comment]
@dovy yes this should be fixed. @partnuz is right about the issue with themeforest.

**Comment by awps** [comment]
First of all the developer must check the value. Every option from SMOF has a default value which is '`'`(empty) or is set by developer(this is `std`). So, if you want to echo something, you must check is is set. Do it that way:

``` php
//Check if is set
$option_value = ( isset($smof_data[$id]) ) ? $smof_data[$id] : 'use this value';

//return the result
echo $option_value;
```

Or better to have a function, so later you can make changes only from one place(this function):

``` php
if ( ! function_exists('smk_get_option_data') ) {
    function smk_get_option_data($id, $fallback = false) {
        global $smof_data;
        $output = ( isset($smof_data[$id]) ) ? $smof_data[$id] : $fallback;
        return $output;
    }
}
```

use it:

``` php
echo smk_get_option_data('the_id_from_smof', 'value_to_return_if_not_set');
```

And forget about "Undefined index" notices.

**Comment by dovy** [comment]
@chadhenry @Smartik89 @partnuz 

Umm, it's not really an issue. If you add a value and visit any page in the admin section, it resolves the issue. I really doubt a user will upgrade the theme every without being logged into wp-admin...

Am I wrong?

**Pull request merged**
