### PR TITLE
Update options head w/ theme version

### PR DESCRIPTION
**Pull request by mechabyte**
I might've accidentally proposed this file change but this is the final one :P

### CODE REVIEW

**Comment by syamilmj** [comment]
Cool stuff thanks ;)

**Comment by mechabyte** [comment]
Eek! Patch-4 is missing the css styling. Merge the one from patch-3, haha.

**Comment by mechabyte** [comment]
I keep messing up on these pull requests

**Comment by mechabyte** [comment]
Fixed CSS in patch-5.

**Pull request merged**
